### ISSUE TITLE
Alternatives Layout

### ISSUE THREAD

**Issue by hemaanjo** [ch570512/Qlockwork#10]
Hallo würde gerne mein Layout implementieren.
Verwende original Biegert & Funk Front.
Zusätzlich gibt es bei meiner Variante noch 120Leds wovon jeweils 2 LEDs die Sekunden anzeigen.
Kurze Hilfe wo man am besten das Layout ergänzt wäre nett.
Danke vorab
Josef

**Comment by ch570512** [comment]
Hallo

Um das Layout der Uhr zu erweitern müssten grosse Teile des Codes neu geschrieben werden.
Es gibt keine "Stelle" welche man ändern könnte da sich die 11x10 Matrix überall im Code wiederfindet.
Ich kann bei diesem Vorhaben nicht unterstützen.

Grüße
Thorsten
