### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by maghostmil** [ch570512/Qlockwork#4]
Do you have a font which you used to your face-clock?
I create a 60x60 cm version, but I can't find this font in internet.

**Comment by ch570512** [comment]
Hi. I only use the original fronts from qlocktwo. never made a front by my
own. sorry.
best regards

Marcin Świerczek <notifications@github.com> schrieb am Mo., 21. Dez. 2020,
17:08:

**Comment by ch570512** [comment]
I only use the original fronts from qlocktwo. Never made a front by my own. Sorry.
