### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by BornTKill** [ch570512/Qlockwork#5]
Dear @ch570512 

First of All, I would like to congrats you for this awesome project. Love it !

i am building qlockwork (French Language) with 
LED_LAYOUT_VERTICAL_2 layout.
My question is, can you explain me how 110,111,112,113 and 114 are supposed to work ?

Best regards and Happy New Year.

**Comment by GenosseFlosse** [comment]
Hi @BornTKill, LEDs 110-113 are the minutes indicators. so when it's 15:17, two leds out of 110-113 will be on. The number of Leds is equal to ```nleds = minutes % 5```. You can change the order of the leds in the matrices in LedDriver.cpp. I myself have not found out which function 114 has.

Here the corner LEDs are set: https://github.com/ch570512/Qlockwork/blob/4a03458aa9386fefd14105241fbab1f44ad08e65/Qlockwork.ino#L860

**Comment by BornTKill** [comment]
Hi @GenosseFlosse 

Thank you for your answer.

ok so only 110,112 and 113 can lights ?
On my side 111 and 114 are never switched on.

same for you @GenosseFlosse ?

PS: i have test my stripe with another project (wled) and all leds are OK.

**Comment by GenosseFlosse** [comment]
Pardon, I messed up. In LED_LAYOUT_VERTICAL_2 111 has no minute function but is the alarm LED.
Have you changed the order in Line 
https://github.com/ch570512/Qlockwork/blob/4a03458aa9386fefd14105241fbab1f44ad08e65/LedDriver.cpp#L78
and checked whether it works then? 114 should work normally. At which times do LEDs 110,112 and 113 switch on?

You can also try and check the DEBUG_MATRIX option where the ESP puts it's matrix output into the serial monitor

**Comment by BornTKill** [comment]
@GenosseFlosse 
At 15:01 : led 112 ON
At 15:02 : led 112 ON
At 15:03 : led 112, 110 ON
At 15:04 : led 113, 112, 110 ON

114 and 111 always off.

**Comment by GenosseFlosse** [comment]
Mmmh and in LED test mode every LED works?
And are you sure you did not change anything accidentally in the repository?

I HAVE AN IDEA! @BornTKill
Try changing https://github.com/ch570512/Qlockwork/blob/4a03458aa9386fefd14105241fbab1f44ad08e65/Configuration.h#L106
to 115 and let us know if it worked

**Comment by BornTKill** [comment]
I have change nothing regarding led number. Just set

#define NEOPIXEL_TYPE NEO_**RGB** + NEO_KHZ800

All led are OK with https://github.com/Aircoookie/WLED but in qlockwork test mod they are not. Gonna try you proposal. Let you know

**Comment by BornTKill** [comment]
Hey !

that’s ok now :)
Thank you for your support !

one more thing : 
What is the best way « print » the front ?

**Comment by GenosseFlosse** [comment]
So my proposal worked?

I am quite shure this is the reason. As you can see in 
https://github.com/adafruit/Adafruit_NeoPixel/blob/8595ee3f5880d5096d71551c621d7a2d3818f974/Adafruit_NeoPixel.cpp#L2258
the LED is not switched on if n < numLEDs. But in 
https://github.com/ch570512/Qlockwork/blob/4a03458aa9386fefd14105241fbab1f44ad08e65/LedDriver.cpp#L9
We initialize numPixels as 114. And as 114 !< 114, the LED is just not switched on.

**Comment by GenosseFlosse** [comment]
I have my local lasercutting shop cut it for me in 500mm x 500mm from 3mm MDF "wood".

**Comment by BornTKill** [comment]
Yes your solution work like a charm :)

can you share pic ?
My prototype is made of craft 🤣

**Comment by GenosseFlosse** [comment]
As you can see I prepared a quick PR so that other users do not run into the same problem :)

I cannot send a pic because I'm not at my clock's place. 
But it kinda looks like [this one](https://www.google.com/search?q=wordclock&tbm=isch#imgrc=OmJsPRXxrd7vcM).
I spraypainted the MDF in black and put 4mm acrylic glass in front. That looks kinda awesome.

Btw @BornTKill you can close the Issue now since your problem is resolved.

**Comment by BornTKill** [comment]
Thank you for the PR and your help !
